DROP TABLE IF EXISTS book_genres;

DROP TABLE IF EXISTS genres;

DROP TABLE IF EXISTS reading_histories;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS books;

DROP TABLE IF EXISTS authors;

DROP TABLE IF EXISTS publishers;

DROP TYPE if EXISTS reading_status;