// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: book_genre.sql

package db

import (
	"context"
)

const getBooksByGenreName = `-- name: GetBooksByGenreName :many
SELECT book_id
FROM book_genres
WHERE genre_name = $1
`

func (q *Queries) GetBooksByGenreName(ctx context.Context, genreName string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByGenreName, genreName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var book_id int64
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenresByBookID = `-- name: GetGenresByBookID :many
SELECT genre_name
FROM book_genres
WHERE book_id = $1
`

func (q *Queries) GetGenresByBookID(ctx context.Context, bookID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getGenresByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var genre_name string
		if err := rows.Scan(&genre_name); err != nil {
			return nil, err
		}
		items = append(items, genre_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBookGenre = `-- name: InsertBookGenre :exec
INSERT INTO book_genres (book_id, genre_name)
VALUES ($1, $2)
`

type InsertBookGenreParams struct {
	BookID    int64  `json:"book_id"`
	GenreName string `json:"genre_name"`
}

func (q *Queries) InsertBookGenre(ctx context.Context, arg InsertBookGenreParams) error {
	_, err := q.db.ExecContext(ctx, insertBookGenre, arg.BookID, arg.GenreName)
	return err
}

const updateGenreForBook = `-- name: UpdateGenreForBook :exec
UPDATE book_genres
SET genre_name = $3
WHERE book_id = $1
  AND genre_name = $2
`

type UpdateGenreForBookParams struct {
	BookID      int64  `json:"book_id"`
	GenreName   string `json:"genre_name"`
	GenreName_2 string `json:"genre_name_2"`
}

func (q *Queries) UpdateGenreForBook(ctx context.Context, arg UpdateGenreForBookParams) error {
	_, err := q.db.ExecContext(ctx, updateGenreForBook, arg.BookID, arg.GenreName, arg.GenreName_2)
	return err
}
