// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: book_genre.sql

package db

import (
	"context"
)

const createBookGenre = `-- name: CreateBookGenre :one
INSERT INTO book_genres (book_id, genre_name)
VALUES ($1, $2) RETURNING book_id, genre_name
`

type CreateBookGenreParams struct {
	BookID    int64  `json:"book_id"`
	GenreName string `json:"genre_name"`
}

func (q *Queries) CreateBookGenre(ctx context.Context, arg CreateBookGenreParams) (BookGenre, error) {
	row := q.db.QueryRowContext(ctx, createBookGenre, arg.BookID, arg.GenreName)
	var i BookGenre
	err := row.Scan(&i.BookID, &i.GenreName)
	return i, err
}

const deleteBookGenre = `-- name: DeleteBookGenre :execrows
DELETE
FROM book_genres
WHERE book_id = $1
  AND genre_name = $2
`

type DeleteBookGenreParams struct {
	BookID    int64  `json:"book_id"`
	GenreName string `json:"genre_name"`
}

func (q *Queries) DeleteBookGenre(ctx context.Context, arg DeleteBookGenreParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBookGenre, arg.BookID, arg.GenreName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGenresByBookID = `-- name: GetGenresByBookID :many
SELECT genre_name
FROM book_genres
WHERE book_id = $1
`

func (q *Queries) GetGenresByBookID(ctx context.Context, bookID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getGenresByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var genre_name string
		if err := rows.Scan(&genre_name); err != nil {
			return nil, err
		}
		items = append(items, genre_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
