// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ReadingStatus string

const (
	ReadingStatusUnread  ReadingStatus = "unread"
	ReadingStatusReading ReadingStatus = "reading"
	ReadingStatusDone    ReadingStatus = "done"
	ReadingStatusUnknown ReadingStatus = "unknown"
)

func (e *ReadingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReadingStatus(s)
	case string:
		*e = ReadingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReadingStatus: %T", src)
	}
	return nil
}

type NullReadingStatus struct {
	ReadingStatus ReadingStatus `json:"reading_status"`
	Valid         bool          `json:"valid"` // Valid is true if ReadingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReadingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReadingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReadingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReadingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReadingStatus), nil
}

// Stores author data.
type Author struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

// Stores book data.
type Book struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Url           sql.NullString `json:"url"`
	AuthorName    sql.NullString `json:"author_name"`
	PublisherName sql.NullString `json:"publisher_name"`
	PublishedDate sql.NullTime   `json:"published_date"`
	Isbn          sql.NullString `json:"isbn"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// Stores book and genre. Normalize using intermediate tables because of the many-to-many relationship between books and genres.
type BookGenre struct {
	BookID    int64  `json:"book_id"`
	GenreName string `json:"genre_name"`
}

type Books0 struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Url           sql.NullString `json:"url"`
	AuthorName    sql.NullString `json:"author_name"`
	PublisherName sql.NullString `json:"publisher_name"`
	PublishedDate sql.NullTime   `json:"published_date"`
	Isbn          sql.NullString `json:"isbn"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Books1 struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Url           sql.NullString `json:"url"`
	AuthorName    sql.NullString `json:"author_name"`
	PublisherName sql.NullString `json:"publisher_name"`
	PublishedDate sql.NullTime   `json:"published_date"`
	Isbn          sql.NullString `json:"isbn"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Books2 struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Url           sql.NullString `json:"url"`
	AuthorName    sql.NullString `json:"author_name"`
	PublisherName sql.NullString `json:"publisher_name"`
	PublishedDate sql.NullTime   `json:"published_date"`
	Isbn          sql.NullString `json:"isbn"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Books3 struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Url           sql.NullString `json:"url"`
	AuthorName    sql.NullString `json:"author_name"`
	PublisherName sql.NullString `json:"publisher_name"`
	PublishedDate sql.NullTime   `json:"published_date"`
	Isbn          sql.NullString `json:"isbn"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// Stores genre data.
type Genre struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

// Stores publisher data.
type Publisher struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type ReadingHistoriesDefault struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m01 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m02 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m03 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m04 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m05 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m06 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m07 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m08 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m09 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m10 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m11 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2025m12 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m01 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m02 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m03 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m04 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m05 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m06 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m07 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m08 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m09 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m10 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m11 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ReadingHistoriesY2026m12 struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

// Stores reading history.
type ReadingHistory struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

// Stores session data.
type Session struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsDefault struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m01 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m02 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m03 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m04 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m05 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m06 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m07 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m08 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m09 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m10 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m11 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2025m12 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m01 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m02 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m03 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m04 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m05 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m06 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m07 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m08 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m09 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m10 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m11 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type SessionsY2026m12 struct {
	ID           uuid.UUID      `json:"id"`
	UserID       int64          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Revoked      bool           `json:"revoked"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

// Stores user data.
type User struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
