// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: publisher.sql

package db

import (
	"context"
)

const createPublisher = `-- name: CreatePublisher :one
INSERT INTO publishers (name)
VALUES ($1) RETURNING name, created_at
`

func (q *Queries) CreatePublisher(ctx context.Context, name string) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, createPublisher, name)
	var i Publisher
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}

const deletePublisher = `-- name: DeletePublisher :exec
DELETE
FROM publishers
WHERE name = $1
`

func (q *Queries) DeletePublisher(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePublisher, name)
	return err
}

const getAllPublishers = `-- name: GetAllPublishers :many
SELECT name, created_at
FROM publishers LIMIT $1
OFFSET $2
`

type GetAllPublishersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllPublishers(ctx context.Context, arg GetAllPublishersParams) ([]Publisher, error) {
	rows, err := q.db.QueryContext(ctx, getAllPublishers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Publisher{}
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(&i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublisherByName = `-- name: GetPublisherByName :one
SELECT name, created_at
FROM publishers
WHERE name = $1
`

func (q *Queries) GetPublisherByName(ctx context.Context, name string) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, getPublisherByName, name)
	var i Publisher
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}
