// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	DeleteGenre(ctx context.Context, name string) error
	GetAllGenres(ctx context.Context) ([]Genre, error)
	GetGenreByName(ctx context.Context, name string) (Genre, error)
	InsertGenre(ctx context.Context, name string) (Genre, error)
}

var _ Querier = (*Queries)(nil)
