// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reading_history.sql

package db

import (
	"context"
	"database/sql"
)

const createReadingHistory = `-- name: CreateReadingHistory :one
INSERT INTO reading_histories (user_id, book_id, status, start_date, end_date)
VALUES ($1, $2, $3, $4, $5) RETURNING user_id, book_id, status, start_date, end_date, created_at, updated_at
`

type CreateReadingHistoryParams struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
}

func (q *Queries) CreateReadingHistory(ctx context.Context, arg CreateReadingHistoryParams) (ReadingHistory, error) {
	row := q.db.QueryRowContext(ctx, createReadingHistory,
		arg.UserID,
		arg.BookID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var i ReadingHistory
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReadingHistory = `-- name: DeleteReadingHistory :exec
DELETE
FROM reading_histories
WHERE user_id = $1
  AND book_id = $2
`

type DeleteReadingHistoryParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) DeleteReadingHistory(ctx context.Context, arg DeleteReadingHistoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadingHistory, arg.UserID, arg.BookID)
	return err
}

const getReadingHistoryByUserAndBook = `-- name: GetReadingHistoryByUserAndBook :one
SELECT user_id, book_id, status, start_date, end_date, created_at, updated_at
FROM reading_histories
WHERE user_id = $1
  AND book_id = $2
`

type GetReadingHistoryByUserAndBookParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) GetReadingHistoryByUserAndBook(ctx context.Context, arg GetReadingHistoryByUserAndBookParams) (ReadingHistory, error) {
	row := q.db.QueryRowContext(ctx, getReadingHistoryByUserAndBook, arg.UserID, arg.BookID)
	var i ReadingHistory
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingHistoryByUserAndStatus = `-- name: GetReadingHistoryByUserAndStatus :many
SELECT user_id, book_id, status, start_date, end_date, created_at, updated_at
FROM reading_histories
WHERE user_id = $1
  AND status = $2
ORDER BY status LIMIT $3
OFFSET $4
`

type GetReadingHistoryByUserAndStatusParams struct {
	UserID int64         `json:"user_id"`
	Status ReadingStatus `json:"status"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) GetReadingHistoryByUserAndStatus(ctx context.Context, arg GetReadingHistoryByUserAndStatusParams) ([]ReadingHistory, error) {
	rows, err := q.db.QueryContext(ctx, getReadingHistoryByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingHistory{}
	for rows.Next() {
		var i ReadingHistory
		if err := rows.Scan(
			&i.UserID,
			&i.BookID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingHistoryByUserID = `-- name: GetReadingHistoryByUserID :many
SELECT user_id, book_id, status, start_date, end_date, created_at, updated_at
FROM reading_histories
WHERE user_id = $1
ORDER BY user_id LIMIT $2
OFFSET $3
`

type GetReadingHistoryByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetReadingHistoryByUserID(ctx context.Context, arg GetReadingHistoryByUserIDParams) ([]ReadingHistory, error) {
	rows, err := q.db.QueryContext(ctx, getReadingHistoryByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingHistory{}
	for rows.Next() {
		var i ReadingHistory
		if err := rows.Scan(
			&i.UserID,
			&i.BookID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReadingHistory = `-- name: UpdateReadingHistory :one
UPDATE reading_histories
SET status     = $3,
    start_date = $4,
    end_date   = $5,
    updated_at = now()
WHERE user_id = $1
  AND book_id = $2 RETURNING user_id, book_id, status, start_date, end_date, created_at, updated_at
`

type UpdateReadingHistoryParams struct {
	UserID    int64         `json:"user_id"`
	BookID    int64         `json:"book_id"`
	Status    ReadingStatus `json:"status"`
	StartDate sql.NullTime  `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
}

func (q *Queries) UpdateReadingHistory(ctx context.Context, arg UpdateReadingHistoryParams) (ReadingHistory, error) {
	row := q.db.QueryRowContext(ctx, updateReadingHistory,
		arg.UserID,
		arg.BookID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var i ReadingHistory
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
