// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: book.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genres        []string               `protobuf:"bytes,3,rep,name=genres,proto3" json:"genres,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CoverImageUrl *string                `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	Url           *string                `protobuf:"bytes,6,opt,name=url,proto3,oneof" json:"url,omitempty"`
	AuthorName    *string                `protobuf:"bytes,7,opt,name=author_name,json=authorName,proto3,oneof" json:"author_name,omitempty"`
	PublisherName *string                `protobuf:"bytes,8,opt,name=publisher_name,json=publisherName,proto3,oneof" json:"publisher_name,omitempty"`
	PublishDate   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=publish_date,json=publishDate,proto3,oneof" json:"publish_date,omitempty"`
	Isbn          *string                `protobuf:"bytes,10,opt,name=isbn,proto3,oneof" json:"isbn,omitempty"`
	ReadingStatus ReadingStatus          `protobuf:"varint,11,opt,name=reading_status,json=readingStatus,proto3,enum=pb.ReadingStatus" json:"reading_status,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Book) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Book) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *Book) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Book) GetAuthorName() string {
	if x != nil && x.AuthorName != nil {
		return *x.AuthorName
	}
	return ""
}

func (x *Book) GetPublisherName() string {
	if x != nil && x.PublisherName != nil {
		return *x.PublisherName
	}
	return ""
}

func (x *Book) GetPublishDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishDate
	}
	return nil
}

func (x *Book) GetIsbn() string {
	if x != nil && x.Isbn != nil {
		return *x.Isbn
	}
	return ""
}

func (x *Book) GetReadingStatus() ReadingStatus {
	if x != nil {
		return x.ReadingStatus
	}
	return ReadingStatus_UNREAD
}

func (x *Book) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Book) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

var File_book_proto protoreflect.FileDescriptor

const file_book_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"book.proto\x12\x02pb\x1a\x14reading_status.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x05\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06genres\x18\x03 \x03(\tR\x06genres\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tH\x01R\rcoverImageUrl\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x06 \x01(\tH\x02R\x03url\x88\x01\x01\x12$\n" +
	"\vauthor_name\x18\a \x01(\tH\x03R\n" +
	"authorName\x88\x01\x01\x12*\n" +
	"\x0epublisher_name\x18\b \x01(\tH\x04R\rpublisherName\x88\x01\x01\x12B\n" +
	"\fpublish_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x05R\vpublishDate\x88\x01\x01\x12\x17\n" +
	"\x04isbn\x18\n" +
	" \x01(\tH\x06R\x04isbn\x88\x01\x01\x128\n" +
	"\x0ereading_status\x18\v \x01(\x0e2\x11.pb.ReadingStatusR\rreadingStatus\x12>\n" +
	"\n" +
	"start_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\aR\tstartDate\x88\x01\x01\x12:\n" +
	"\bend_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\bR\aendDate\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_cover_image_urlB\x06\n" +
	"\x04_urlB\x0e\n" +
	"\f_author_nameB\x11\n" +
	"\x0f_publisher_nameB\x0f\n" +
	"\r_publish_dateB\a\n" +
	"\x05_isbnB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateBF\n" +
	"\x06com.pbB\tBookProtoP\x01Z\treadly/pb\xa2\x02\x03PXX\xaa\x02\x02Pb\xca\x02\x02Pb\xe2\x02\x0ePb\\GPBMetadata\xea\x02\x02Pbb\x06proto3"

var (
	file_book_proto_rawDescOnce sync.Once
	file_book_proto_rawDescData []byte
)

func file_book_proto_rawDescGZIP() []byte {
	file_book_proto_rawDescOnce.Do(func() {
		file_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_proto_rawDesc), len(file_book_proto_rawDesc)))
	})
	return file_book_proto_rawDescData
}

var file_book_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_proto_goTypes = []any{
	(*Book)(nil),                  // 0: pb.Book
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(ReadingStatus)(0),            // 2: pb.ReadingStatus
}
var file_book_proto_depIdxs = []int32{
	1, // 0: pb.Book.publish_date:type_name -> google.protobuf.Timestamp
	2, // 1: pb.Book.reading_status:type_name -> pb.ReadingStatus
	1, // 2: pb.Book.start_date:type_name -> google.protobuf.Timestamp
	1, // 3: pb.Book.end_date:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_book_proto_init() }
func file_book_proto_init() {
	if File_book_proto != nil {
		return
	}
	file_reading_status_proto_init()
	file_book_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_proto_rawDesc), len(file_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_book_proto_goTypes,
		DependencyIndexes: file_book_proto_depIdxs,
		MessageInfos:      file_book_proto_msgTypes,
	}.Build()
	File_book_proto = out.File
	file_book_proto_goTypes = nil
	file_book_proto_depIdxs = nil
}
