// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: reading_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadingStatus int32

const (
	ReadingStatus_UNREAD  ReadingStatus = 0
	ReadingStatus_READING ReadingStatus = 1
	ReadingStatus_DONE    ReadingStatus = 2
	ReadingStatus_UNKNOWN ReadingStatus = 3
)

// Enum value maps for ReadingStatus.
var (
	ReadingStatus_name = map[int32]string{
		0: "UNREAD",
		1: "READING",
		2: "DONE",
		3: "UNKNOWN",
	}
	ReadingStatus_value = map[string]int32{
		"UNREAD":  0,
		"READING": 1,
		"DONE":    2,
		"UNKNOWN": 3,
	}
)

func (x ReadingStatus) Enum() *ReadingStatus {
	p := new(ReadingStatus)
	*p = x
	return p
}

func (x ReadingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_reading_status_proto_enumTypes[0].Descriptor()
}

func (ReadingStatus) Type() protoreflect.EnumType {
	return &file_reading_status_proto_enumTypes[0]
}

func (x ReadingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadingStatus.Descriptor instead.
func (ReadingStatus) EnumDescriptor() ([]byte, []int) {
	return file_reading_status_proto_rawDescGZIP(), []int{0}
}

var File_reading_status_proto protoreflect.FileDescriptor

const file_reading_status_proto_rawDesc = "" +
	"\n" +
	"\x14reading_status.proto\x12\x02pb*?\n" +
	"\rReadingStatus\x12\n" +
	"\n" +
	"\x06UNREAD\x10\x00\x12\v\n" +
	"\aREADING\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x03BO\n" +
	"\x06com.pbB\x12ReadingStatusProtoP\x01Z\treadly/pb\xa2\x02\x03PXX\xaa\x02\x02Pb\xca\x02\x02Pb\xe2\x02\x0ePb\\GPBMetadata\xea\x02\x02Pbb\x06proto3"

var (
	file_reading_status_proto_rawDescOnce sync.Once
	file_reading_status_proto_rawDescData []byte
)

func file_reading_status_proto_rawDescGZIP() []byte {
	file_reading_status_proto_rawDescOnce.Do(func() {
		file_reading_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reading_status_proto_rawDesc), len(file_reading_status_proto_rawDesc)))
	})
	return file_reading_status_proto_rawDescData
}

var file_reading_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reading_status_proto_goTypes = []any{
	(ReadingStatus)(0), // 0: pb.ReadingStatus
}
var file_reading_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reading_status_proto_init() }
func file_reading_status_proto_init() {
	if File_reading_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reading_status_proto_rawDesc), len(file_reading_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reading_status_proto_goTypes,
		DependencyIndexes: file_reading_status_proto_depIdxs,
		EnumInfos:         file_reading_status_proto_enumTypes,
	}.Build()
	File_reading_status_proto = out.File
	file_reading_status_proto_goTypes = nil
	file_reading_status_proto_depIdxs = nil
}
