// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: reading_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadingStatus int32

const (
	ReadingStatus_UNREAD  ReadingStatus = 0
	ReadingStatus_READING ReadingStatus = 1
	ReadingStatus_DONE    ReadingStatus = 2
	ReadingStatus_UNKNOWN ReadingStatus = 3
)

// Enum value maps for ReadingStatus.
var (
	ReadingStatus_name = map[int32]string{
		0: "UNREAD",
		1: "READING",
		2: "DONE",
		3: "UNKNOWN",
	}
	ReadingStatus_value = map[string]int32{
		"UNREAD":  0,
		"READING": 1,
		"DONE":    2,
		"UNKNOWN": 3,
	}
)

func (x ReadingStatus) Enum() *ReadingStatus {
	p := new(ReadingStatus)
	*p = x
	return p
}

func (x ReadingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_reading_status_proto_enumTypes[0].Descriptor()
}

func (ReadingStatus) Type() protoreflect.EnumType {
	return &file_reading_status_proto_enumTypes[0]
}

func (x ReadingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadingStatus.Descriptor instead.
func (ReadingStatus) EnumDescriptor() ([]byte, []int) {
	return file_reading_status_proto_rawDescGZIP(), []int{0}
}

var File_reading_status_proto protoreflect.FileDescriptor

var file_reading_status_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x3f, 0x0a, 0x0d, 0x52, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x55,
	0x4e, 0x52, 0x45, 0x41, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x41, 0x44, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x42, 0x0b, 0x5a, 0x09, 0x72,
	0x65, 0x61, 0x64, 0x6c, 0x79, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_reading_status_proto_rawDescOnce sync.Once
	file_reading_status_proto_rawDescData []byte
)

func file_reading_status_proto_rawDescGZIP() []byte {
	file_reading_status_proto_rawDescOnce.Do(func() {
		file_reading_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reading_status_proto_rawDesc), len(file_reading_status_proto_rawDesc)))
	})
	return file_reading_status_proto_rawDescData
}

var file_reading_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reading_status_proto_goTypes = []any{
	(ReadingStatus)(0), // 0: pb.ReadingStatus
}
var file_reading_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reading_status_proto_init() }
func file_reading_status_proto_init() {
	if File_reading_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reading_status_proto_rawDesc), len(file_reading_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reading_status_proto_goTypes,
		DependencyIndexes: file_reading_status_proto_depIdxs,
		EnumInfos:         file_reading_status_proto_enumTypes,
	}.Build()
	File_reading_status_proto = out.File
	file_reading_status_proto_goTypes = nil
	file_reading_status_proto_depIdxs = nil
}
