// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service_user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_user_proto protoreflect.FileDescriptor

const file_service_user_proto_rawDesc = "" +
	"\n" +
	"\x12service_user.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x17rpc_refresh_token.proto\x1a\x11rpc_sign_in.proto\x1a\x11rpc_sign_up.proto2\xfe\x01\n" +
	"\vUserService\x12F\n" +
	"\x06SignIn\x12\x11.pb.SignInRequest\x1a\x12.pb.SignInResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/signin\x12F\n" +
	"\x06SignUp\x12\x11.pb.SignUpRequest\x1a\x12.pb.SignUpResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/signup\x12_\n" +
	"\fRefreshToken\x12\x17.pb.RefreshTokenRequest\x1a\x18.pb.RefreshTokenResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/refresh-tokenBM\n" +
	"\x06com.pbB\x10ServiceUserProtoP\x01Z\treadly/pb\xa2\x02\x03PXX\xaa\x02\x02Pb\xca\x02\x02Pb\xe2\x02\x0ePb\\GPBMetadata\xea\x02\x02Pbb\x06proto3"

var file_service_user_proto_goTypes = []any{
	(*SignInRequest)(nil),        // 0: pb.SignInRequest
	(*SignUpRequest)(nil),        // 1: pb.SignUpRequest
	(*RefreshTokenRequest)(nil),  // 2: pb.RefreshTokenRequest
	(*SignInResponse)(nil),       // 3: pb.SignInResponse
	(*SignUpResponse)(nil),       // 4: pb.SignUpResponse
	(*RefreshTokenResponse)(nil), // 5: pb.RefreshTokenResponse
}
var file_service_user_proto_depIdxs = []int32{
	0, // 0: pb.UserService.SignIn:input_type -> pb.SignInRequest
	1, // 1: pb.UserService.SignUp:input_type -> pb.SignUpRequest
	2, // 2: pb.UserService.RefreshToken:input_type -> pb.RefreshTokenRequest
	3, // 3: pb.UserService.SignIn:output_type -> pb.SignInResponse
	4, // 4: pb.UserService.SignUp:output_type -> pb.SignUpResponse
	5, // 5: pb.UserService.RefreshToken:output_type -> pb.RefreshTokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_user_proto_init() }
func file_service_user_proto_init() {
	if File_service_user_proto != nil {
		return
	}
	file_rpc_refresh_token_proto_init()
	file_rpc_sign_in_proto_init()
	file_rpc_sign_up_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_user_proto_rawDesc), len(file_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_proto_goTypes,
		DependencyIndexes: file_service_user_proto_depIdxs,
	}.Build()
	File_service_user_proto = out.File
	file_service_user_proto_goTypes = nil
	file_service_user_proto_depIdxs = nil
}
