// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service_book.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_book_proto protoreflect.FileDescriptor

const file_service_book_proto_rawDesc = "" +
	"\n" +
	"\x12service_book.proto\x12\x02pb\x1a\n" +
	"book.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15rpc_delete_book.proto\x1a\x17rpc_register_book.proto2\xb0\x01\n" +
	"\vBookService\x12G\n" +
	"\fRegisterBook\x12\x17.pb.RegisterBookRequest\x1a\b.pb.Book\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/books\x12X\n" +
	"\n" +
	"DeleteBook\x12\x15.pb.DeleteBookRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/books/{book_id}BM\n" +
	"\x06com.pbB\x10ServiceBookProtoP\x01Z\treadly/pb\xa2\x02\x03PXX\xaa\x02\x02Pb\xca\x02\x02Pb\xe2\x02\x0ePb\\GPBMetadata\xea\x02\x02Pbb\x06proto3"

var file_service_book_proto_goTypes = []any{
	(*RegisterBookRequest)(nil), // 0: pb.RegisterBookRequest
	(*DeleteBookRequest)(nil),   // 1: pb.DeleteBookRequest
	(*Book)(nil),                // 2: pb.Book
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_service_book_proto_depIdxs = []int32{
	0, // 0: pb.BookService.RegisterBook:input_type -> pb.RegisterBookRequest
	1, // 1: pb.BookService.DeleteBook:input_type -> pb.DeleteBookRequest
	2, // 2: pb.BookService.RegisterBook:output_type -> pb.Book
	3, // 3: pb.BookService.DeleteBook:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_book_proto_init() }
func file_service_book_proto_init() {
	if File_service_book_proto != nil {
		return
	}
	file_book_proto_init()
	file_rpc_delete_book_proto_init()
	file_rpc_register_book_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_book_proto_rawDesc), len(file_service_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_book_proto_goTypes,
		DependencyIndexes: file_service_book_proto_depIdxs,
	}.Build()
	File_service_book_proto = out.File
	file_service_book_proto_goTypes = nil
	file_service_book_proto_depIdxs = nil
}
