// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: readly/v1/reading_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadingStatus int32

const (
	ReadingStatus_READING_STATUS_UNREAD_UNSPECIFIED ReadingStatus = 0
	ReadingStatus_READING_STATUS_READING            ReadingStatus = 1
	ReadingStatus_READING_STATUS_DONE               ReadingStatus = 2
	ReadingStatus_READING_STATUS_UNKNOWN            ReadingStatus = 3
)

// Enum value maps for ReadingStatus.
var (
	ReadingStatus_name = map[int32]string{
		0: "READING_STATUS_UNREAD_UNSPECIFIED",
		1: "READING_STATUS_READING",
		2: "READING_STATUS_DONE",
		3: "READING_STATUS_UNKNOWN",
	}
	ReadingStatus_value = map[string]int32{
		"READING_STATUS_UNREAD_UNSPECIFIED": 0,
		"READING_STATUS_READING":            1,
		"READING_STATUS_DONE":               2,
		"READING_STATUS_UNKNOWN":            3,
	}
)

func (x ReadingStatus) Enum() *ReadingStatus {
	p := new(ReadingStatus)
	*p = x
	return p
}

func (x ReadingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_readly_v1_reading_status_proto_enumTypes[0].Descriptor()
}

func (ReadingStatus) Type() protoreflect.EnumType {
	return &file_readly_v1_reading_status_proto_enumTypes[0]
}

func (x ReadingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadingStatus.Descriptor instead.
func (ReadingStatus) EnumDescriptor() ([]byte, []int) {
	return file_readly_v1_reading_status_proto_rawDescGZIP(), []int{0}
}

var File_readly_v1_reading_status_proto protoreflect.FileDescriptor

const file_readly_v1_reading_status_proto_rawDesc = "" +
	"\n" +
	"\x1ereadly/v1/reading_status.proto\x12\treadly.v1*\x87\x01\n" +
	"\rReadingStatus\x12%\n" +
	"!READING_STATUS_UNREAD_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16READING_STATUS_READING\x10\x01\x12\x17\n" +
	"\x13READING_STATUS_DONE\x10\x02\x12\x1a\n" +
	"\x16READING_STATUS_UNKNOWN\x10\x03B\x80\x01\n" +
	"\rcom.readly.v1B\x12ReadingStatusProtoP\x01Z\x16readly/pb/readly/v1;pb\xa2\x02\x03RXX\xaa\x02\tReadly.V1\xca\x02\tReadly\\V1\xe2\x02\x15Readly\\V1\\GPBMetadata\xea\x02\n" +
	"Readly::V1b\x06proto3"

var (
	file_readly_v1_reading_status_proto_rawDescOnce sync.Once
	file_readly_v1_reading_status_proto_rawDescData []byte
)

func file_readly_v1_reading_status_proto_rawDescGZIP() []byte {
	file_readly_v1_reading_status_proto_rawDescOnce.Do(func() {
		file_readly_v1_reading_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_readly_v1_reading_status_proto_rawDesc), len(file_readly_v1_reading_status_proto_rawDesc)))
	})
	return file_readly_v1_reading_status_proto_rawDescData
}

var file_readly_v1_reading_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_readly_v1_reading_status_proto_goTypes = []any{
	(ReadingStatus)(0), // 0: readly.v1.ReadingStatus
}
var file_readly_v1_reading_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_readly_v1_reading_status_proto_init() }
func file_readly_v1_reading_status_proto_init() {
	if File_readly_v1_reading_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readly_v1_reading_status_proto_rawDesc), len(file_readly_v1_reading_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_readly_v1_reading_status_proto_goTypes,
		DependencyIndexes: file_readly_v1_reading_status_proto_depIdxs,
		EnumInfos:         file_readly_v1_reading_status_proto_enumTypes,
	}.Build()
	File_readly_v1_reading_status_proto = out.File
	file_readly_v1_reading_status_proto_goTypes = nil
	file_readly_v1_reading_status_proto_depIdxs = nil
}
