// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: readly/v1/rpc_register_book.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Genres        []string               `protobuf:"bytes,2,rep,name=genres,proto3" json:"genres,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CoverImageUrl *string                `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	Url           *string                `protobuf:"bytes,5,opt,name=url,proto3,oneof" json:"url,omitempty"`
	AuthorName    *string                `protobuf:"bytes,6,opt,name=author_name,json=authorName,proto3,oneof" json:"author_name,omitempty"`
	PublisherName *string                `protobuf:"bytes,7,opt,name=publisher_name,json=publisherName,proto3,oneof" json:"publisher_name,omitempty"`
	PublishDate   *Date                  `protobuf:"bytes,8,opt,name=publish_date,json=publishDate,proto3,oneof" json:"publish_date,omitempty"`
	Isbn          *string                `protobuf:"bytes,9,opt,name=isbn,proto3,oneof" json:"isbn,omitempty"`
	ReadingStatus ReadingStatus          `protobuf:"varint,10,opt,name=reading_status,json=readingStatus,proto3,enum=readly.v1.ReadingStatus" json:"reading_status,omitempty"`
	StartDate     *Date                  `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *Date                  `protobuf:"bytes,12,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBookRequest) Reset() {
	*x = RegisterBookRequest{}
	mi := &file_readly_v1_rpc_register_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBookRequest) ProtoMessage() {}

func (x *RegisterBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readly_v1_rpc_register_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBookRequest.ProtoReflect.Descriptor instead.
func (*RegisterBookRequest) Descriptor() ([]byte, []int) {
	return file_readly_v1_rpc_register_book_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RegisterBookRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *RegisterBookRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RegisterBookRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *RegisterBookRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *RegisterBookRequest) GetAuthorName() string {
	if x != nil && x.AuthorName != nil {
		return *x.AuthorName
	}
	return ""
}

func (x *RegisterBookRequest) GetPublisherName() string {
	if x != nil && x.PublisherName != nil {
		return *x.PublisherName
	}
	return ""
}

func (x *RegisterBookRequest) GetPublishDate() *Date {
	if x != nil {
		return x.PublishDate
	}
	return nil
}

func (x *RegisterBookRequest) GetIsbn() string {
	if x != nil && x.Isbn != nil {
		return *x.Isbn
	}
	return ""
}

func (x *RegisterBookRequest) GetReadingStatus() ReadingStatus {
	if x != nil {
		return x.ReadingStatus
	}
	return ReadingStatus_UNREAD
}

func (x *RegisterBookRequest) GetStartDate() *Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *RegisterBookRequest) GetEndDate() *Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type RegisterBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBookResponse) Reset() {
	*x = RegisterBookResponse{}
	mi := &file_readly_v1_rpc_register_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBookResponse) ProtoMessage() {}

func (x *RegisterBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_readly_v1_rpc_register_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBookResponse.ProtoReflect.Descriptor instead.
func (*RegisterBookResponse) Descriptor() ([]byte, []int) {
	return file_readly_v1_rpc_register_book_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

var File_readly_v1_rpc_register_book_proto protoreflect.FileDescriptor

const file_readly_v1_rpc_register_book_proto_rawDesc = "" +
	"\n" +
	"!readly/v1/rpc_register_book.proto\x12\treadly.v1\x1a\x14readly/v1/book.proto\x1a\x14readly/v1/date.proto\x1a\x1ereadly/v1/reading_status.proto\"\xfe\x04\n" +
	"\x13RegisterBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06genres\x18\x02 \x03(\tR\x06genres\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tH\x01R\rcoverImageUrl\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x05 \x01(\tH\x02R\x03url\x88\x01\x01\x12$\n" +
	"\vauthor_name\x18\x06 \x01(\tH\x03R\n" +
	"authorName\x88\x01\x01\x12*\n" +
	"\x0epublisher_name\x18\a \x01(\tH\x04R\rpublisherName\x88\x01\x01\x127\n" +
	"\fpublish_date\x18\b \x01(\v2\x0f.readly.v1.DateH\x05R\vpublishDate\x88\x01\x01\x12\x17\n" +
	"\x04isbn\x18\t \x01(\tH\x06R\x04isbn\x88\x01\x01\x12?\n" +
	"\x0ereading_status\x18\n" +
	" \x01(\x0e2\x18.readly.v1.ReadingStatusR\rreadingStatus\x123\n" +
	"\n" +
	"start_date\x18\v \x01(\v2\x0f.readly.v1.DateH\aR\tstartDate\x88\x01\x01\x12/\n" +
	"\bend_date\x18\f \x01(\v2\x0f.readly.v1.DateH\bR\aendDate\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_cover_image_urlB\x06\n" +
	"\x04_urlB\x0e\n" +
	"\f_author_nameB\x11\n" +
	"\x0f_publisher_nameB\x0f\n" +
	"\r_publish_dateB\a\n" +
	"\x05_isbnB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\";\n" +
	"\x14RegisterBookResponse\x12#\n" +
	"\x04book\x18\x01 \x01(\v2\x0f.readly.v1.BookR\x04bookB\x82\x01\n" +
	"\rcom.readly.v1B\x14RpcRegisterBookProtoP\x01Z\x16readly/pb/readly/v1;pb\xa2\x02\x03RXX\xaa\x02\tReadly.V1\xca\x02\tReadly\\V1\xe2\x02\x15Readly\\V1\\GPBMetadata\xea\x02\n" +
	"Readly::V1b\x06proto3"

var (
	file_readly_v1_rpc_register_book_proto_rawDescOnce sync.Once
	file_readly_v1_rpc_register_book_proto_rawDescData []byte
)

func file_readly_v1_rpc_register_book_proto_rawDescGZIP() []byte {
	file_readly_v1_rpc_register_book_proto_rawDescOnce.Do(func() {
		file_readly_v1_rpc_register_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_readly_v1_rpc_register_book_proto_rawDesc), len(file_readly_v1_rpc_register_book_proto_rawDesc)))
	})
	return file_readly_v1_rpc_register_book_proto_rawDescData
}

var file_readly_v1_rpc_register_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_readly_v1_rpc_register_book_proto_goTypes = []any{
	(*RegisterBookRequest)(nil),  // 0: readly.v1.RegisterBookRequest
	(*RegisterBookResponse)(nil), // 1: readly.v1.RegisterBookResponse
	(*Date)(nil),                 // 2: readly.v1.Date
	(ReadingStatus)(0),           // 3: readly.v1.ReadingStatus
	(*Book)(nil),                 // 4: readly.v1.Book
}
var file_readly_v1_rpc_register_book_proto_depIdxs = []int32{
	2, // 0: readly.v1.RegisterBookRequest.publish_date:type_name -> readly.v1.Date
	3, // 1: readly.v1.RegisterBookRequest.reading_status:type_name -> readly.v1.ReadingStatus
	2, // 2: readly.v1.RegisterBookRequest.start_date:type_name -> readly.v1.Date
	2, // 3: readly.v1.RegisterBookRequest.end_date:type_name -> readly.v1.Date
	4, // 4: readly.v1.RegisterBookResponse.book:type_name -> readly.v1.Book
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_readly_v1_rpc_register_book_proto_init() }
func file_readly_v1_rpc_register_book_proto_init() {
	if File_readly_v1_rpc_register_book_proto != nil {
		return
	}
	file_readly_v1_book_proto_init()
	file_readly_v1_date_proto_init()
	file_readly_v1_reading_status_proto_init()
	file_readly_v1_rpc_register_book_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readly_v1_rpc_register_book_proto_rawDesc), len(file_readly_v1_rpc_register_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_readly_v1_rpc_register_book_proto_goTypes,
		DependencyIndexes: file_readly_v1_rpc_register_book_proto_depIdxs,
		MessageInfos:      file_readly_v1_rpc_register_book_proto_msgTypes,
	}.Build()
	File_readly_v1_rpc_register_book_proto = out.File
	file_readly_v1_rpc_register_book_proto_goTypes = nil
	file_readly_v1_rpc_register_book_proto_depIdxs = nil
}
