// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: readly/v1/rpc_get_book_list.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookListRequest) Reset() {
	*x = GetBookListRequest{}
	mi := &file_readly_v1_rpc_get_book_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookListRequest) ProtoMessage() {}

func (x *GetBookListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readly_v1_rpc_get_book_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookListRequest.ProtoReflect.Descriptor instead.
func (*GetBookListRequest) Descriptor() ([]byte, []int) {
	return file_readly_v1_rpc_get_book_list_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetBookListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetBookListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookListResponse) Reset() {
	*x = GetBookListResponse{}
	mi := &file_readly_v1_rpc_get_book_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookListResponse) ProtoMessage() {}

func (x *GetBookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_readly_v1_rpc_get_book_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookListResponse.ProtoReflect.Descriptor instead.
func (*GetBookListResponse) Descriptor() ([]byte, []int) {
	return file_readly_v1_rpc_get_book_list_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookListResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_readly_v1_rpc_get_book_list_proto protoreflect.FileDescriptor

const file_readly_v1_rpc_get_book_list_proto_rawDesc = "" +
	"\n" +
	"!readly/v1/rpc_get_book_list.proto\x12\treadly.v1\x1a\x14readly/v1/book.proto\"B\n" +
	"\x12GetBookListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"<\n" +
	"\x13GetBookListResponse\x12%\n" +
	"\x05books\x18\x01 \x03(\v2\x0f.readly.v1.BookR\x05booksB\x81\x01\n" +
	"\rcom.readly.v1B\x13RpcGetBookListProtoP\x01Z\x16readly/pb/readly/v1;pb\xa2\x02\x03RXX\xaa\x02\tReadly.V1\xca\x02\tReadly\\V1\xe2\x02\x15Readly\\V1\\GPBMetadata\xea\x02\n" +
	"Readly::V1b\x06proto3"

var (
	file_readly_v1_rpc_get_book_list_proto_rawDescOnce sync.Once
	file_readly_v1_rpc_get_book_list_proto_rawDescData []byte
)

func file_readly_v1_rpc_get_book_list_proto_rawDescGZIP() []byte {
	file_readly_v1_rpc_get_book_list_proto_rawDescOnce.Do(func() {
		file_readly_v1_rpc_get_book_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_readly_v1_rpc_get_book_list_proto_rawDesc), len(file_readly_v1_rpc_get_book_list_proto_rawDesc)))
	})
	return file_readly_v1_rpc_get_book_list_proto_rawDescData
}

var file_readly_v1_rpc_get_book_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_readly_v1_rpc_get_book_list_proto_goTypes = []any{
	(*GetBookListRequest)(nil),  // 0: readly.v1.GetBookListRequest
	(*GetBookListResponse)(nil), // 1: readly.v1.GetBookListResponse
	(*Book)(nil),                // 2: readly.v1.Book
}
var file_readly_v1_rpc_get_book_list_proto_depIdxs = []int32{
	2, // 0: readly.v1.GetBookListResponse.books:type_name -> readly.v1.Book
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_readly_v1_rpc_get_book_list_proto_init() }
func file_readly_v1_rpc_get_book_list_proto_init() {
	if File_readly_v1_rpc_get_book_list_proto != nil {
		return
	}
	file_readly_v1_book_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readly_v1_rpc_get_book_list_proto_rawDesc), len(file_readly_v1_rpc_get_book_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_readly_v1_rpc_get_book_list_proto_goTypes,
		DependencyIndexes: file_readly_v1_rpc_get_book_list_proto_depIdxs,
		MessageInfos:      file_readly_v1_rpc_get_book_list_proto_msgTypes,
	}.Build()
	File_readly_v1_rpc_get_book_list_proto = out.File
	file_readly_v1_rpc_get_book_list_proto_goTypes = nil
	file_readly_v1_rpc_get_book_list_proto_depIdxs = nil
}
