// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: readly/v1/service_user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_readly_v1_service_user_proto protoreflect.FileDescriptor

const file_readly_v1_service_user_proto_rawDesc = "" +
	"\n" +
	"\x1creadly/v1/service_user.proto\x12\treadly.v1\x1a\x1cgoogle/api/annotations.proto\x1a!readly/v1/rpc_refresh_token.proto\x1a\x1breadly/v1/rpc_sign_in.proto\x1a\x1breadly/v1/rpc_sign_up.proto2\xa8\x02\n" +
	"\vUserService\x12T\n" +
	"\x06SignIn\x12\x18.readly.v1.SignInRequest\x1a\x19.readly.v1.SignInResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/signin\x12T\n" +
	"\x06SignUp\x12\x18.readly.v1.SignUpRequest\x1a\x19.readly.v1.SignUpResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/signup\x12m\n" +
	"\fRefreshToken\x12\x1e.readly.v1.RefreshTokenRequest\x1a\x1f.readly.v1.RefreshTokenResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/refresh-tokenB~\n" +
	"\rcom.readly.v1B\x10ServiceUserProtoP\x01Z\x16readly/pb/readly/v1;pb\xa2\x02\x03RXX\xaa\x02\tReadly.V1\xca\x02\tReadly\\V1\xe2\x02\x15Readly\\V1\\GPBMetadata\xea\x02\n" +
	"Readly::V1b\x06proto3"

var file_readly_v1_service_user_proto_goTypes = []any{
	(*SignInRequest)(nil),        // 0: readly.v1.SignInRequest
	(*SignUpRequest)(nil),        // 1: readly.v1.SignUpRequest
	(*RefreshTokenRequest)(nil),  // 2: readly.v1.RefreshTokenRequest
	(*SignInResponse)(nil),       // 3: readly.v1.SignInResponse
	(*SignUpResponse)(nil),       // 4: readly.v1.SignUpResponse
	(*RefreshTokenResponse)(nil), // 5: readly.v1.RefreshTokenResponse
}
var file_readly_v1_service_user_proto_depIdxs = []int32{
	0, // 0: readly.v1.UserService.SignIn:input_type -> readly.v1.SignInRequest
	1, // 1: readly.v1.UserService.SignUp:input_type -> readly.v1.SignUpRequest
	2, // 2: readly.v1.UserService.RefreshToken:input_type -> readly.v1.RefreshTokenRequest
	3, // 3: readly.v1.UserService.SignIn:output_type -> readly.v1.SignInResponse
	4, // 4: readly.v1.UserService.SignUp:output_type -> readly.v1.SignUpResponse
	5, // 5: readly.v1.UserService.RefreshToken:output_type -> readly.v1.RefreshTokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_readly_v1_service_user_proto_init() }
func file_readly_v1_service_user_proto_init() {
	if File_readly_v1_service_user_proto != nil {
		return
	}
	file_readly_v1_rpc_refresh_token_proto_init()
	file_readly_v1_rpc_sign_in_proto_init()
	file_readly_v1_rpc_sign_up_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readly_v1_service_user_proto_rawDesc), len(file_readly_v1_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_readly_v1_service_user_proto_goTypes,
		DependencyIndexes: file_readly_v1_service_user_proto_depIdxs,
	}.Build()
	File_readly_v1_service_user_proto = out.File
	file_readly_v1_service_user_proto_goTypes = nil
	file_readly_v1_service_user_proto_depIdxs = nil
}
