// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: readly/v1/service_book.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_readly_v1_service_book_proto protoreflect.FileDescriptor

const file_readly_v1_service_book_proto_rawDesc = "" +
	"\n" +
	"\x1creadly/v1/service_book.proto\x12\treadly.v1\x1a\x14readly/v1/book.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1freadly/v1/rpc_delete_book.proto\x1a!readly/v1/rpc_register_book.proto2\xc5\x01\n" +
	"\vBookService\x12U\n" +
	"\fRegisterBook\x12\x1e.readly.v1.RegisterBookRequest\x1a\x0f.readly.v1.Book\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/books\x12_\n" +
	"\n" +
	"DeleteBook\x12\x1c.readly.v1.DeleteBookRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/books/{book_id}Bq\n" +
	"\rcom.readly.v1B\x10ServiceBookProtoP\x01Z\treadly/pb\xa2\x02\x03RXX\xaa\x02\tReadly.V1\xca\x02\tReadly\\V1\xe2\x02\x15Readly\\V1\\GPBMetadata\xea\x02\n" +
	"Readly::V1b\x06proto3"

var file_readly_v1_service_book_proto_goTypes = []any{
	(*RegisterBookRequest)(nil), // 0: readly.v1.RegisterBookRequest
	(*DeleteBookRequest)(nil),   // 1: readly.v1.DeleteBookRequest
	(*Book)(nil),                // 2: readly.v1.Book
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_readly_v1_service_book_proto_depIdxs = []int32{
	0, // 0: readly.v1.BookService.RegisterBook:input_type -> readly.v1.RegisterBookRequest
	1, // 1: readly.v1.BookService.DeleteBook:input_type -> readly.v1.DeleteBookRequest
	2, // 2: readly.v1.BookService.RegisterBook:output_type -> readly.v1.Book
	3, // 3: readly.v1.BookService.DeleteBook:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_readly_v1_service_book_proto_init() }
func file_readly_v1_service_book_proto_init() {
	if File_readly_v1_service_book_proto != nil {
		return
	}
	file_readly_v1_book_proto_init()
	file_readly_v1_rpc_delete_book_proto_init()
	file_readly_v1_rpc_register_book_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readly_v1_service_book_proto_rawDesc), len(file_readly_v1_service_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_readly_v1_service_book_proto_goTypes,
		DependencyIndexes: file_readly_v1_service_book_proto_depIdxs,
	}.Build()
	File_readly_v1_service_book_proto = out.File
	file_readly_v1_service_book_proto_goTypes = nil
	file_readly_v1_service_book_proto_depIdxs = nil
}
